apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-splitter-pod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-splitter-pod
  template:
    metadata:
      labels:
        app: name-splitter-pod
    spec:
      runtimeClassName: wasmedge
      containers:
        - name: name-splitter-pod
          image: ghcr.io/second-state/name-splitter-pod:latest
          imagePullPolicy: Never
          command: ["name-splitter-pod.wasm"]
          ports:
            - containerPort: 90
          # generic stuff below - maybe not needed
          env:
            - name: WASMEDGE_PLUGIN_PATH
              value: "/home/dev/.wasmedge/plugin"
            - name: LD_LIBRARY_PATH
              value: "/home/dev/.wasmedge/lib"
          volumeMounts:
            - name: wasi-nn-plugin-file
              mountPath: /home/dev/.wasmedge/plugin/libwasmedgePluginWasiNN.so
              readOnly: true
            - name: wasi-nn-plugin-lib
              mountPath: /home/dev/.wasmedge/lib
              readOnly: true
            - name: libm
              mountPath: /lib/aarch64-linux-gnu/libm.so.6
              readOnly: true
            - name: libpthread
              mountPath: /lib/aarch64-linux-gnu/libpthread.so.0
              readOnly: true
            - name: libc
              mountPath: /lib/aarch64-linux-gnu/libc.so.6
              readOnly: true
            - name: ld-linux
              mountPath: /lib/ld-linux-aarch64.so.1
              readOnly: true
            - name: libdl
              mountPath: /lib/aarch64-linux-gnu/libdl.so.2
              readOnly: true
            - name: libstdcxx
              mountPath: /lib/aarch64-linux-gnu/libstdc++.so.6
              readOnly: true
            - name: libgcc-s
              mountPath: /lib/aarch64-linux-gnu/libgcc-s.so.1
              readOnly: true
      volumes:
        - name: wasi-nn-plugin-file
          hostPath:
            path: /home/dev/.wasmedge/plugin/libwasmedgePluginWasiNN.so
            type: File
        - name: wasi-nn-plugin-lib
          hostPath:
            path: /home/dev/.wasmedge/lib
            type: Directory
        - name: libm
          hostPath:
            path: /lib/aarch64-linux-gnu/libm.so.6
            type: File
        - name: libpthread
          hostPath:
            path: /lib/aarch64-linux-gnu/libpthread.so.0
            type: File
        - name: libc
          hostPath:
            path: /lib/aarch64-linux-gnu/libc.so.6
            type: File
        - name: ld-linux
          hostPath:
            path: /lib/ld-linux-aarch64.so.1
            type: File
        - name: libdl
          hostPath:
            path: /lib/aarch64-linux-gnu/libdl.so.2
            type: File
        - name: libstdcxx
          hostPath:
            path: /lib/aarch64-linux-gnu/libstdc++.so.6
            type: File
        - name: libgcc-s
          hostPath:
            path: /lib/aarch64-linux-gnu/libgcc_s.so.1
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: name-splitter-pod-service
spec:
  type: NodePort
  selector:
    app: name-splitter-pod
  ports:
    - targetPort: 90
      port: 90
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-greeter-pod-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: name-greeter-pod
  template:
    metadata:
      labels:
        app: name-greeter-pod
    spec:
      runtimeClassName: wasmedge
      containers:
        - name: name-greeter-pod
          image: ghcr.io/second-state/name-greeter-pod:latest
          imagePullPolicy: Never
          command: ["name-greeter-pod.wasm"]
          ports:
            - containerPort: 80
          # generic stuff below - maybe not needed
          env:
            - name: WASMEDGE_PLUGIN_PATH
              value: "/home/dev/.wasmedge/plugin"
            - name: LD_LIBRARY_PATH
              value: "/home/dev/.wasmedge/lib"
          volumeMounts:
            - name: wasi-nn-plugin-file
              mountPath: /home/dev/.wasmedge/plugin/libwasmedgePluginWasiNN.so
              readOnly: true
            - name: wasi-nn-plugin-lib
              mountPath: /home/dev/.wasmedge/lib
              readOnly: true
            - name: libm
              mountPath: /lib/aarch64-linux-gnu/libm.so.6
              readOnly: true
            - name: libpthread
              mountPath: /lib/aarch64-linux-gnu/libpthread.so.0
              readOnly: true
            - name: libc
              mountPath: /lib/aarch64-linux-gnu/libc.so.6
              readOnly: true
            - name: ld-linux
              mountPath: /lib/ld-linux-aarch64.so.1
              readOnly: true
            - name: libdl
              mountPath: /lib/aarch64-linux-gnu/libdl.so.2
              readOnly: true
            - name: libstdcxx
              mountPath: /lib/aarch64-linux-gnu/libstdc++.so.6
              readOnly: true
            - name: libgcc-s
              mountPath: /lib/aarch64-linux-gnu/libgcc-s.so.1
              readOnly: true
      volumes:
        - name: wasi-nn-plugin-file
          hostPath:
            path: /home/dev/.wasmedge/plugin/libwasmedgePluginWasiNN.so
            type: File
        - name: wasi-nn-plugin-lib
          hostPath:
            path: /home/dev/.wasmedge/lib
            type: Directory
        - name: libm
          hostPath:
            path: /lib/aarch64-linux-gnu/libm.so.6
            type: File
        - name: libpthread
          hostPath:
            path: /lib/aarch64-linux-gnu/libpthread.so.0
            type: File
        - name: libc
          hostPath:
            path: /lib/aarch64-linux-gnu/libc.so.6
            type: File
        - name: ld-linux
          hostPath:
            path: /lib/ld-linux-aarch64.so.1
            type: File
        - name: libdl
          hostPath:
            path: /lib/aarch64-linux-gnu/libdl.so.2
            type: File
        - name: libstdcxx
          hostPath:
            path: /lib/aarch64-linux-gnu/libstdc++.so.6
            type: File
        - name: libgcc-s
          hostPath:
            path: /lib/aarch64-linux-gnu/libgcc_s.so.1
            type: File

---
apiVersion: v1
kind: Service
metadata:
  name: name-greeter-pod-service
spec:
  type: ClusterIP
  selector:
    app: name-greeter-pod
  ports:
    - port: 70
      targetPort: 80
---

# debugging purpose only - NodePort service for greeter pods
apiVersion: v1
kind: Service
metadata:
  name: name-greeter-pod-nodeport-service
spec:
  type: NodePort
  selector:
    app: name-greeter-pod
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002


---
# runtime info
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmedge
handler: wasmedge
